
name: Mock Developer Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Code
        uses: actions/checkout@v4

      - name: Fake Build Step
        run: |
          echo "Building a virtual container..."
          echo "IMAGE_TAG=mock-app-v1.0" >> $GITHUB_ENV

      # This is where U (Security) come in
      - name: Run Security Check
        uses: Halimatcd/SEC@main
        with:
          image-name: ${{ env.IMAGE_TAG }}
   
